# Generated by Django 4.2.4 on 2023-09-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter the username from twitter/fb', max_length=50)),
                ('post_code', models.TextField(help_text='Enter the embed url', max_length=1000)),
                ('post_text', models.TextField(help_text='Enter the text portion of the post', max_length=200)),
                ('like_count', models.IntegerField()),
                ('post_trend', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['like_count'],
            },
        ),
    ]
