# Generated by Django 4.2.4 on 2023-09-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-like_count']},
        ),
    ]
